prefix gvp: <http://vocab.getty.edu/ontology#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rel: <http://ldf.fi/schema/relations/>


CONSTRUCT {
  ?person rdfs:label ?name .
  }
 WHERE {
  ?personConcept a gvp:PersonConcept;
      gvp:prefLabelGVP/gvp:term ?name;
      foaf:focus ?person .
}
