prefix gvp: <http://vocab.getty.edu/ontology#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rel: <http://ldf.fi/schema/relations/>


CONSTRUCT {
  ?newURI rdfs:label ?name .
  }
 WHERE {
  ?personConcept a gvp:PersonConcept;
      gvp:prefLabelGVP/gvp:term ?label.

  BIND(STR(?label) AS ?name)
  BIND(STRAFTER(str(?personConcept), "/ulan/") AS ?id)
  BIND(URI(CONCAT("http://ldf.fi/ulan/", ?id)) AS ?newURI)

}
